local M = {
  documents = {
    Default = "",
    File = "",
    Files = "",
    FileFind = "󰈞",
    FileTree = "󰙅",
    Word = "",
  },
  git = {
    Add = "",
    Branch = "",
    Diff = "",
    Git = "󰊢",
    Remove = "",
    Rename = "",
    Repo = "",
    Unstaged = "",
    Staged = "",
    Conflict = "",
    Ignore = "",
  },
  ui = {
    Bug = "",
    Buffer = "󰓩",
    Close = "󰅖",
    CodeAction = "󰌵",
    Comment = "󰅺",
    Dashboard = "",
    FolderOpen = "",
    FolderWithHeart = "󱃪",
    Gear = "",
    History = "󰄉",
    Left = "",
    List = "",
    Lock = "󰍁",
    NewFile = "",
    Package = "",
    Pencil = "󰏫",
    Play = "",
    Right = "",
    Search = "󰍉",
    Separator = "",
    Telescope = "",
    Window = "",
    Folder = "",
    Circle = "",
    Check = "󰄳",
    ChevronRight = "",
    Fire = "",
    Keyboard = "",
    Note = "󰍨",
    Table = "",
    Tab = "",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "",
    Hint = "󰌵",
  },
  misc = {
    Add = "+",
    Ghost = "󰊠",
    Glass = "󰂖",
    LspAvailable = "󱜙",
    Neovim = "",
    Tag = "",
    Tree = "",
    Vbar = "│",
    Code = "",
    Squirrel = "",
    Watch = "",
  },
  kind = {
    Class = "󰠱",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    Field = "󰇽",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Keyword = "󰌋",
    Method = "󰆧",
    Module = "",
    Namespace = "󰌗",
    Operator = "󰆕",
    Property = "󰜢",
    Snippet = "",
    Struct = "",
    Text = "󰉿",
    Value = "󰎠",
    Variable = "",
  },
  dap = {
    Breakpoint = "󰝥",
    BreakpointCondition = "󰟃",
    BreakpointRejected = "󰈸",
    Stopped = "",
    LogPoint = "󰘛",
  },
  aichat = {
    Chat = "󰭻",
    User = "",
    Assistant = "󰚩",
  },
}

local kind_icons = {
  Class = "󰠱",
  Constant = "󰏿",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "󰇽",
  File = "󰈙",
  Folder = "󰉋",
  Function = "󰊕",
  Interface = "",
  Keyword = "󰋌",
  Method = "󰆧",
  Module = "",
  Namespace = "󰌗",
  Null = "󰟢",
  Number = "",
  Operator = "󰆕",
  Package = "",
  Property = "󰜢",
  Reference = "",
  Snippet = "",
  String = "󰉿",
  Struct = "",
  Text = "󰉿",
  TypeParameter = "󰅲",
  Unit = "",
  Value = "󰎠",
  Variable = "",
}

function M.get_kind()
  return kind_icons
end

return M
