export ANTHROPIC_BASE_URL="https://api.aslnet.cloud"
export ANTHROPIC_MODEL="claude-sonnet-4-5"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export CLAUDE_CODE_ATTRIBUTION_HEADER=0
export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
export CLAUDE_CODE_EFFORT_LEVEL="max"
